// frontend/led-matrix/src/components/nav/Navbar.tsx
import { Jumbotron } from "../../App";

export default function Navbar({ jumbotron, setJumbotron }: { jumbotron: Jumbotron, setJumbotron: Function }) {
    return (
        <nav className="bg-gray-900 p-4 min-w-full absolute top-0 left-0 right-0 z-50 flex">
            <div className="container mx-auto gap-4 flex justify-between items-center">
                <h2 className="text-green-300 text-xl">{`${jumbotron.rows}R x ${jumbotron.columns}C`}</h2>
                <h2 className="text-blue-400 text-xl">{jumbotron.ip}</h2>
                <button className="bg-red-600" onClick={() => setJumbotron(null)}>Exit</button>
            </div>
        </nav>
    );
}

// frontend/jumbotron/src/components/Navbar.svelte
<script lang="ts">
    import { jumbotronInstance, Jumbotron } from '../classes/Jumbotron';

    let jumbotronState: Jumbotron;

    jumbotronInstance.subscribe((state) => {
        jumbotronState = state;
    });

    async function disconnect() {
        await jumbotronInstance.disconnect();
    }
</script>

<nav class="absolute w-full left-0 top-0">
    {#if jumbotronState}
        <div class="navbar bg-base-100">
            <div class="navbar-start">
                <h2>{jumbotronState.rows} Rows X {jumbotronState.columns} Columns</h2>
            </div>
            <div class="navbar-center flex">
                <h2 class="font-bold text-3xl">{jumbotronState.hostname}:{jumbotronState.port}</h2>
            </div>
            <div class="navbar-end">
                <button class="bg-red-800" on:click={disconnect}>Disconnect</button>
            </div>
        </div>
    {/if}
</nav>

<style>
</style>
